name: 'Login aws'
description: 'Log into aws for a kubernetes deployment using helmfile'
inputs:
  awskeys:  
    required: true
    description: "JSON object with keys aws_access_key_id and aws_secret_access_key"
  cluster-name:  
    required: true
  aws-region:
    required: true
outputs:
  helmfile-creds:
    value: ${{ steps.set-helmfile.outputs.creds }}
    
runs:
  using: "composite"
  steps:

    - name: Set provider
      id: set-cloud-info
      uses: actions/github-script@v4
      env:
        awskeys: ${{ inputs.awskeys }}
      with:
        result-encoding: json
        script: |
          const awsCreds = JSON.parse(process.env.awskeys);
          return awsCreds;
          core.setSecret(awsCreds.aws_access_key_id);
          core.setSecret(awsCreds.aws_secret_access_key);

    - name: AWS Setup / AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ fromJSON(steps.set-cloud-info.outputs.result).aws_access_key_id }}
        aws-secret-access-key: ${{ fromJSON(steps.set-cloud-info.outputs.result).aws_secret_access_key }}
        aws-region: ${{ inputs.aws-region }}
    
    - name: AWS Setup/ Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: AWS Setup / update kubeconfig
      shell: bash
      run: |
            mkdir -p ~/.kube
            aws eks update-kubeconfig --name ${{ inputs.cluster-name }}

    - id: set-helmfile
      shell: bash
      run: |
        export HELMFILE_CREDS=$(aws ecr get-login-password)
        echo "::set-output name=creds::$(echo $HELMFILE_CREDS)"